
tree: tree-try.o tree.o proc-common.o
        gcc -o tree tree.o tree-try.o proc-common.o
tree-try.o: tree-try.c
        gcc -Wall -c tree-try.c
tree.o: tree.c
        gcc -c tree.c
proc-common.o: proc-common.c
        gcc -c proc-common.c
